defaults:
  -
    scope:
      path: "sites"
    values:
      layout: "single-col"


port: 4001

repository: unm-digital-history/campus-history

baseurl: campus-history/

essay-images: /essays/images
